name: mycelium.threefold.io 
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest changes on mycelium.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: mycelium.threefold.io
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www_mycelium
          git log -1
          git fetch
          git reset --hard origin/master
          sed -i "s/https:\/\/www2.mycelium.threefold.io/https:\/\/mycelium.threefold.io/g" config.toml
          ./build.sh

  wait:
    needs: deploy
    name: Wait for Website Update
    runs-on: ubuntu-latest
    steps:
    - name: Wait Period
      id: wait-deploy
      run: |
        echo "Sleeping for 30"
        sleep 30
        
  checklinks:
    needs: wait
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Check for Broken Links
        id: link-report
        uses: docker://ghcr.io/threefoldfoundation/website-link-checker:latest
        with:
          args: 'https://www.mycelium.threefold.io -w 404'